In [58]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import SGDClassifier
from sklearn import svm

In [43]:
dataset = 'C://Users//H//Desktop//Spring18//-AdvancedDatabases//Project//Project_Work//final_binary_dataset.csv'
data = pd.read_csv(dataset, encoding='utf-8-sig')

In [78]:
training = data.iloc[: 200]
testing = data.iloc[200 :]

labels = ['For guns', 'Against guns']
features_train = training['For guns'].values
features_test = testing['For guns'].values
tweet_train = training['Tweet']
tweet_test = testing['Tweet']


features_train0 = training[training['For guns'] == 0]
print(len(features_train0))
features_train1 = training[training['For guns'] == 1]
print(len((features_train1)))
combinedfeaturestrain = features_train0.iloc[: 71]
combinedfeaturestrain = combinedfeaturestrain.append(features_train1)
print(len(combinedfeaturestrain))
print(combinedfeaturestrain)

features_train = combinedfeaturestrain['For guns'].values
tweet_train = combinedfeaturestrain['Tweet']

129
71
142
                                                 Tweet  For guns?  \
0    @Mary_rnntt2 @lauren_hoggs You're blinded by y...        0.0   
1    Hey #MNLEG, don’t be idiotic. gun laws, not pa...        0.0   
2    Gun owners, women, kids, all opposed to the ab...        0.0   
3    @PhilipRucker Is he taking guns away from ment...        0.0   
9    White House vows to help arm teachers and back...        0.0   
10   @realDonaldTrump\r\r\r\r\nlies, like other peo...        0.0   
15   Whatever helps the @NRA sell more guns.\r\r\r\...        0.0   
18   @matthewamiller Let’s  allow all persons age 1...        0.0   
19   Things white folks talk about a lot. \r\r\r\r\...        0.0   
21   Ideally a safety plan should be able to includ...        0.0   
22   @CNNPolitics @cnnbrk RETURN TO SENDER: IN THE ...        0.0   
23    The @NRA is to Trump what the SS was to Hitler.         0.0   
24   When will people realizing that giving guns to...        0.0   
25   Interesting that t

In [79]:
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(tweet_train)
X_test_counts = count_vect.transform(tweet_test)
print(X_train_counts.shape)
print(X_test_counts.shape)

(142, 1359)
(49, 1359)


In [80]:
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_test_tfidf = tfidf_transformer.transform(X_test_counts)
print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

(142, 1359)
(49, 1359)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:1089: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


In [81]:
clf = MultinomialNB().fit(X_train_tfidf, features_train)

In [82]:
predicted = clf.predict(X_test_tfidf)

In [83]:
np.mean(predicted == features_test)

0.46938775510204084

In [84]:
predicted

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1], dtype=int64)

In [85]:
features_test

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1], dtype=int64)

In [56]:
###################################################
# ####################### SVM #####################
###################################################

In [86]:
clf_svm = svm.SVC()
clf_svm.fit(X_train_tfidf, features_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [87]:
predicted_svm = clf_svm.predict(X_test_tfidf)
predicted

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1], dtype=int64)

In [89]:
np.mean(predicted_svm == features_test)

0.3673469387755102